import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Hero from '@/components/Hero'
import Certification from '@/components/Certification'
import Skills from '@/components/Skills'
import About from '@/components/About'
import LatestWork from '@/components/LatestWork'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className='w-[90%] mx-auto'>
          <Navbar />
        </header>
        <section className='w-[90%] mx-auto'>
          <Hero />
          <Certification />
          <Skills/>
          <About/>
          <LatestWork/>
          <Footer/>
        </section>
        {children}
      </body>
    </html>
  )
}
